GitGaming/urls.py
from django import template
from django.conf.urls import patterns, include, url
from django.contrib import admin
import developers
from django.shortcuts import render_to_response
from portal.views import PortalView, RankingView, BadgeListView
from developers.views import DeveloperProfileEditView
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from GitGaming import settings
from django.contrib.auth.decorators import login_required

admin.autodiscover()

urlpatterns = patterns('',
    # url(r'^$', 'GitGaming.views.home', name='home'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}), #DEBUG
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^auth/', 'githubauth.views.Home', name='home'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),

    #zinnia blog
    url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),

    #Language config
    url(r'^i18n/', include('django.conf.urls.i18n')),
)


urlpatterns += i18n_patterns('',
    url(r'^get_users_ajax/$', "developers.views.get_users", name='get_users_ajax'),
    url(r'^grant_badge/(?P<code>.+)/$', "badges.views.grant_custom_badge", name='grant_custom_badge'),
    url(r'^user/', include('developers.urls')),
    url(r'^edit/$', login_required(DeveloperProfileEditView.as_view()), name='user_edit'),
    url(r'^ranking$', RankingView.as_view(), name='ranking'),
    url(r'^badges$', BadgeListView.as_view(), name='badge_list'),
    url(r'^$', PortalView.as_view(), name='home'),

)

developers/urls.py
from django.conf.urls import patterns, include, url
from views import DeveloperView


urlpatterns = patterns('',
    url(r'^(?P<user>\w+)/$', DeveloperView.as_view(), name='user_detail'),
)

developers/models.py
# from django.conf import settings
from audioop import alaw2lin
from datetime import time
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.translation import ugettext as _
from django.db import models
from django.contrib.auth import get_user_model
from badges.models import Badge
from stats.models import APIStats, UserStats
from badges.tasks import Language, Fidelity, Fork, License
import time
import requests
from image_cropping import ImageRatioField
from GitGaming.SECRET import GITHUB1, GITHUB2
from badges.req import req
from stats.models import APIStats
from skills.models import Skill



# Create your models here.
class Developer(models.Model):
    """ Main User Class
        Every user on the platform will have the following
        information related when 'register' their GitHub User
        for the first time.
    """

    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='django_user')
    githubuser = models.CharField(verbose_name=_('GitHub User account'), max_length=255, null=False, blank=False)
    level = models.IntegerField(verbose_name=_('Current level'), null=True, blank=True, default=1)
    repos = models.IntegerField(null=True, blank=True)
    max_streak = models.IntegerField(null=True, blank=True)
    experience = models.DecimalField(null=True, blank=True, default=0.0, decimal_places=2, max_digits=4)
    register_date = models.DateTimeField(auto_now=True)  # FIXME Deprecated. Migration to delete attr
    last_update = models.DateTimeField(auto_now=True)
    avatar = models.URLField(null=True, blank=True)
    badge = models.ManyToManyField(Badge, through='Achievement')
    points = models.IntegerField(null=False, blank=False, default=100)

    def __unicode__(self):
        return self.githubuser

    def update_profile(self):
        """
            Update Developer Profile and basic information
        """

        profile, created = Profile.objects.get_or_create(dev_user=self)

        # User -------
        url = req['get_user_info'].format(self.githubuser, GITHUB1, GITHUB2)
        info = requests.get(url)

        if settings.DEBUG:
            print "Updating {}".format(profile)

        if not info.from_cache:
            now = time.strftime('%Y-%m-%d')
            api, created = APIStats.objects.get_or_create(date=now)
            api.inc_call()
            api.save()

        info = info.json()


        profile.followers = info[u'followers']
        profile.following = info[u'following']
        self.repos = info[u'public_repos']
        self.save()

        # Repositories
        url = req['get_user_repos'].format(self.githubuser, GITHUB1, GITHUB2)
        repos = requests.get(url)

        if not repos.from_cache:
            now = time.strftime('%Y-%m-%d')
            api, created = APIStats.objects.get_or_create(date=now)
            api.inc_call()
            api.save()

        stars = 0
        forks = 0
        solver = 0

        for repo in repos.json():
            stars += int(repo[u'stargazers_count'])
            forks += int(repo[u'forks_count'])
            solver += int(repo[u'open_issues_count'])

        profile.stars = stars
        profile.forks = forks
        profile.solver = solver
        profile.save()

    def update_skills(self):
        """
            Update Developer skills. (language skills)
        :return:
        """
        url = req['get_user_repos'].format(self.githubuser, GITHUB1, GITHUB2)

        repos = requests.get(url)
        lang_dict = {}

        for repo in repos.json():
            url = repo[u'languages_url']
            url += "?client_id={}&client_secret={}".format(GITHUB1, GITHUB2)
            languages = requests.get(url)

            if settings.DEBUG:
                print 'Skill Checking - From cache: {}'.format(languages.from_cache)

            if not languages.from_cache:
                now = time.strftime('%Y-%m-%d')
                api, created = APIStats.objects.get_or_create(date=now)
                api.inc_call()
                api.save()

            for lang, size in languages.json().iteritems():
                try:
                    lang_dict[lang]
                except KeyError:
                    lang_dict[lang] = 0

                try:
                    lang_dict[lang] += size
                except:
                    pass

        # Update Skills. Note that only 5 skills wil be shown in the View
        for lang, bytes in lang_dict.iteritems():
            s, created = Skill.objects.get_or_create(profile=self.profile, language=lang)
            s.language = lang
            s.profile = self.profile
            s.bytes = bytes

            s.save()

    def grant_badge(self, badge):
        """
            Update Developer Profile and add achievement for a given badge
        """
        a = Achievement()
        a.user = self
        a.badge = badge
        a.save()

        try:
            self.experience
        except:
            self.experience = 0.0

        given_exp = (float(self.experience) + float(badge.experience))

        if given_exp > 100:
            self.level += 1
            self.experience = (given_exp - 100)
        else:
            self.experience = given_exp

        # Update points
        self.points = (self.level * 100) + self.experience
        self.save()

    def check_badges(self):
        """
            With this function, we check over all the badges still not given to a user. If the Developer
            has the
        """

        for badge in Badge.objects.all():
            if not Achievement.objects.filter(user=self, badge=badge):
                if settings.DEBUG:
                    print 'Checking badge: {}'.format(badge)
                # Check all types of badges
                if badge.is_language:
                    b = badge.is_language
                    l = Language
                    if l.check(self.githubuser, b.bytes, b.language):
                        self.grant_badge(b)
                if badge.is_fidelity:
                    b = badge.is_fidelity
                    f = Fidelity
                    if f.check(b.end_date):
                        self.grant_badge(b)
                if badge.is_fork:
                    b = badge.is_fork
                    f = Fork
                    if f.check(self.githubuser, b.forks):
                        self.grant_badge(b)
                if badge.is_license:
                    b = badge.is_license
                    l = License
                    if l.check(self.githubuser, b.license, b.nrepos):
                        self.grant_badge(b)

    def update_data_async(self):
        from worker.tasks import update_developer
        update_developer.s(self.pk).apply_async()


class Achievement(models.Model):
    """
        Achievement class. This model is used to connect Users with Badges. It will have information
        about each badge earned by every user and the date of the achievement.
    """
    date = models.DateField(auto_now=True)
    user = models.ForeignKey(Developer, related_name='developer')
    badge = models.ForeignKey(Badge, related_name='badge')

    def __unicode__(self):
        return 'Achievement {} for user {}'.format(self.badge, self.user)


class Profile(models.Model):
    """ Developer Game Profile
        Each user has a "Gaming profile". It will collect information about
        some basic skills. It's the same as "INTELECT" or "STAMINA" in some videogames.

        It will store also the image that every user can upload to their header profile page. Just like Facebook, etc.
    """
    dev_user = models.OneToOneField(Developer, related_name='profile')
    header = models.ImageField(upload_to='headers', blank=True, null=True)
    header_cropping = ImageRatioField('header', '1170x300')
    bio = models.TextField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    title = models.CharField(null=True, blank=True, max_length=255)
    followers = models.IntegerField(blank=True, null=True, default=0)  # n of followers
    following = models.IntegerField(blank=True, null=True, default=0)  # n of following users
    solver = models.IntegerField(blank=True, null=True, default=0)     # n of open issues in all repos
    stars = models.IntegerField(blank=True, null=True, default=0)      # n of stars in all repos
    forks = models.IntegerField(blank=True, null=True, default=0)      # n of forks in all repos


    def __unicode__(self):
        return 'Profile of: {}'.format(self.dev_user)


def save_user(backend, user, response, *args, **kwargs):
    """
        When an user Login with GitHub, we create a Developer instance
        so we can have an associated Developer profile with that
        authenticated user
    """
    if backend.name == 'github':
        try:
            dev = Developer.objects.get(user=user)
            # If exists, we check for any new update in the repos. Check all the badges
            # FIXME In the future, this function will be called using Celery
            return
        except ObjectDoesNotExist:
            if settings.DEBUG:
                print "Creating new user {}".format(user)

            # Analytics stuff
            now = time.strftime('%Y-%m-%d')
            u, created = UserStats.objects.get_or_create(date=now)
            u.inc_user()
            u.save()

            api, created = APIStats.objects.get_or_create(date=now)
            api.inc_call()
            api.save()

            # Create user
            developer = Developer()
            developer.githubuser = response['login']
            developer.avatar = response['avatar_url']
            developer.repos = response['public_repos']
            developer.user = user
            developer.save()

developers/forms.py
from django import forms
from django.forms import ModelForm
from developers.models import Profile, Achievement
from django.utils.translation import ugettext as _

class DeveloperProfileForm(ModelForm):
    header = forms.ImageField(required=False, widget=forms.FileInput, label=_('Change your header image and crop it!'))
    header_cropping = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(DeveloperProfileForm, self).__init__(*args, **kwargs)
        achievements = Achievement.objects.filter(user=kwargs['instance'].dev_user)
        titles = [("", "No title")]
        for ach in achievements:
            if not ach.badge.title ==  "":
                titles.append((ach.badge.title, ach.badge.title))

        self.fields['title'] = forms.ChoiceField(required=False, label=_('Select your title'),
                                                  choices=titles)

    class Meta:
        model = Profile
        fields = ['header', 'header_cropping', 'bio', 'title', 'website',]

developers/views.py
import re
from django.core.urlresolvers import reverse_lazy, reverse
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from developers.models import Developer, Achievement, Profile
from skills.models import Skill


# Create your views here.
from django.views.generic import TemplateView, FormView, UpdateView
from developers.models import Developer
from .forms import DeveloperProfileForm
import simplejson


class DeveloperView(TemplateView):

    model = Developer
    template_name = 'developers/developer_detail.html'

    def get_context_data(self, **kwargs):
        context = super(DeveloperView, self).get_context_data(**kwargs)
        try:
            developer = Developer.objects.get(githubuser=kwargs['user'])
            context['object'] = developer
            # Call celery task. It will be updating Database in background
            developer.update_data_async()

            #Badges
            context['badges'] = Achievement.objects.filter(user=developer).order_by('-date')

            # Skills and percentages
            skills = Skill.objects.filter(profile=developer.profile)
            sorted_skills = sorted(skills, key=lambda s: s.bytes, reverse=True)
            sorted_skills = sorted_skills[:5]
            try:
                s_max = sorted_skills[0].bytes
            except:
                s_max = 100

            for skill in sorted_skills:
                skill.bytes = format((float(skill.bytes) / float(s_max)) * 100, '.2f')

            context['skills'] = sorted_skills
            return context
        except ObjectDoesNotExist:
            raise Http404()


class DeveloperProfileEditView(UpdateView):
    template_name = 'developers/developer_edit.html'
    success_url = '.'
    form_class = DeveloperProfileForm

    def get_object(self, queryset=None):
        dev = Developer.objects.get(githubuser=self.request.user)
        return Profile.objects.get(dev_user=dev)

    #TODO def form valid


def get_users(request):
    """
    Returns a JSON Object with users. It is used for
    realtime search in Navbar.
    :param request: POST Request with user string
    :return: JSON with all the users
    """
    if request.is_ajax():
        search = request.GET['srsearch']
        regex = re.escape(search)
        print regex
        print search
        devs = Developer.objects.filter(githubuser__icontains=regex)
        response = [{'user': x.githubuser} for x in devs]
        return HttpResponse(simplejson.dumps(response))
    else:
        return HttpResponseRedirect(reverse('home'))

templates/developers/developer_detail.html
{% extends 'base.html' %}
{% load staticfiles i18n thumbnail %}


{% block title %}{{ object }} - {% trans 'Profile' %} GitGaming{% endblock title %}

{% block header %}
    <meta property="og:title" content="{{ object }} {% trans 'Profile' %} GitGaming " />
    <meta property="og:description" content="{{ object }} {% trans 'profile in GitGaming. Check badges, level and much more!' %}" />
    <meta property="og:site_name" content="GitGaming" />
    <meta property="og:image" content="{{ object.avatar }}" />

{% endblock header %}

{% block extra_head %}
    <link href="{% static 'css/social-buttons.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
<style>
    .alert-badge {
        color: #222222;
        background-color: #F5F5F5;
        border-color: #CDCDCD;
    }
</style>

{% endblock extra_head %}

{% block body %}
    <div class="container profile-container">
        <div class="row">

        {% if object.profile.header %}
            {% thumbnail object.profile.header 1170x300 box=object.profile.header_cropping crop detail upscale as header %}
        {% endif %}
        <div class="header" {% if object.profile.header %}style="background-image:url('{{header.url}}')"{% endif %}>

           {% comment %}     <div class="bio-box"><p>{{ object.profile.bio }}</p></div> {% endcomment %}

            <div class="avatar-wrapper">
               <img style="height:175px" class="avatar img-responsive" src="{{ object.avatar }}&s=175">
            </div>
        </div>
            <div class="col-md-12">
                <div class="profile-title row">
                    <h2>{{ object.githubuser }} - {{ object.profile.title }} </h2>
                </div>
            </div>
            <div class="col-md-3">
		{% if user == object.user %}
			<h4>{%  trans 'Request Special Badge' %}</h4>
			<input placeholder="Badge Code" type="text" id="code">
			<a id="request" class="btn btn-success" href="#">{% trans 'Request!' %}</a>
		{% endif %}
                <h4> {% trans 'Level' %}: {{ object.level }}</h4>
                <h4> {% trans 'Experience' %}:</h4>
                <div class="circle text-center" id="circles-1"></div>
                <hr>
                    <h3>{% trans 'Skills' %}</h3>
                    <div>
                        {% for skill in skills %}
                            {{ skill.language }}
                        <div class="progress">
                          <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="{{ skill.bytes }}"
                               aria-valuemin="0" aria-valuemax="100" style="width: {{ skill.bytes }}%;">
                            <span style="color:black">{{ skill.bytes }}%</span>
                          </div>
                        </div>
                        {% endfor %}
                    </div>
                    <canvas id="myChart" width="200" height="200"></canvas>
                {% if object.profile.website %}
                    <p><a href="{{ object.profile.website }}">{% trans 'Personal Website' %}</a></p>
                {% endif %}
                <h4> {{ object.repos }} {% trans 'repositories in the inventory' %} </h4>
            </div>

            <div class="col-md-9">
                <br>
                <div class="alert alert-warning text-center" role="alert">
                    {% blocktrans %}
                        Because this is an Alpha Version, we are calculating your badges right know.
                        If you want to see last changes, wait some minutes and reload the page. We are working to improve this.
                        Sorry for any inconvenience!
                    {% endblocktrans %}

                </div>
            <h3>{% trans 'Share your profile!' %}</h3>
             <div class="social-sharing is-clean text-center">

                <!-- https://developers.facebook.com/docs/plugins/share-button/ -->
                <a target="_blank" href="http://www.facebook.com/sharer.php?u=http://www.gitgaming.com{% url 'user_detail' object.githubuser %}" class="share-facebook">
                  <span class="icon icon-facebook" aria-hidden="true"></span>
                  <span class="share-title">Share</span>
                </a>

                <!-- https://dev.twitter.com/docs/intents -->
                <a target="_blank" href="http://twitter.com/share?url=http://www.gitgaming.com{% url 'user_detail' object.githubuser %};via=gitgaming" class="share-twitter">
                  <span class="icon icon-twitter" aria-hidden="true"></span>
                  <span class="share-title">Tweet</span>
                </a>


                <!-- https://developers.google.com/+/web/share/ -->
                <a target="_blank" href="http://plus.google.com/share?url=http://www.gitgaming.com{% url 'user_detail' object.githubuser %}" class="share-google">
                  <!-- Cannot get Google+ share count with JS yet -->
                  <span class="icon icon-google" aria-hidden="true"></span>
                  <span class="share-title">+1</span>
                </a>

              </div>
                <h3>{% trans 'Last Badges' %}</h3>

                    {% for achievement in badges %}
                        <div class="row ">
                            <div class="animated fadeIn alert alert-badge col-sm-8 col-sm-offset-2 text-center">
                                {% thumbnail achievement.badge.image 75x75 crop detail upscale as badge %}
                                    <img class="img-responsive" style="float:left" src="{{ badge.url }}">
                                    <h4>{{ achievement.badge.name }}</h4>
                                    {{ achievement.badge.description }}
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

{% block extra_body %}

    <script src="{% static 'js/circles.min.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script src="{% static 'js/Chart.Radar.js' %}"></script>
    <script src="{% static 'js/social-buttons.js' %}"></script>
    <script type="text/javascript">
    jQuery('.skillbar').each(function(){
	jQuery(this).find('.skillbar-bar').animate({
		width:jQuery(this).attr('data-percent')
	},2000);
    });
    var myCircle = Circles.create({
          id:           'circles-1',
          radius:       60,
          value:        parseFloat({{ object.experience }}),
          maxValue:     100,
          width:        10,
          text:         function(value){return value + '%';},
          colors:       ['#cbeafc', '#00a1fd'],
          duration:       600,
          wrpClass:     'circles-wrp',
          textClass:    'circles-text',
          styleWrapper: true,
          styleText:    true
        });
        var data = {
            labels: ["Leader", "Social", "Solver", "Famous", "Contributor"],
            datasets: [
                {
                    label: "Skills",
                    fillColor: "rgba(255,187,205,0.4)",
                    strokeColor: "rgba(151,187,205,1)",
                    pointColor: "rgba(151,187,205,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: [
                        {{ object.profile.followers }},
                        {{ object.profile.following }},
                        {{ object.profile.solver }},
                        {{ object.profile.stars }},
                        {{ object.profile.forks }}
                    ]
                }
            ]
        };
        options = {
            scaleShowLabels : false,
            scaleLineColor: "rgba(0,0,0,.4)"

        };

        Chart.defaults.global.responsive = true;
        var ctx = $("#myChart").get(0).getContext("2d");
        var myRadarChart = new Chart(ctx).Radar(data, options);

        $("#code").keyup(function() {
           $("#request").attr('href', '/grant_badge/' + $(this).val());
        });

    </script>
{% endblock extra_body %}

templates/developers/developer_edit.html
{% extends 'base.html' %}
{% load staticfiles i18n thumbnail  crispy_forms_tags%}


{% block title %}{{ user }} - {% trans 'Profile' %} Edit Profile{% endblock title %}

{% block header %}
{% endblock header %}

{% block extra_head %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.guillotine.css' %}" rel="stylesheet">
    <link href="{% static 'css/forms.css' %}" rel="stylesheet">
    <style>
        .avatar-wrapper {
            z-index: 1;
        }
        .guillotine-window {
            height: 300px !important;
        }
    </style>
{% endblock extra_head %}


{% block body %}
    <div class="container profile-container">
        <div class="row">
	{% comment %}
        {% if object.header %}
            {% thumbnail object.header 1170x300 box=object.header_cropping detail upscale as header %}
        {% endif %}
 	{% endcomment %}
        <div class="avatar-wrapper">
           <img style="height:175px;" class="avatar img-responsive" src="{{ object.dev_user.avatar }}">
        </div>
	<!-- TODO: Cargar imagen via ajax? -->
        <div class="header" >
            <img alt="crop img" id="crop" src="" style="display:none">
        </div>

            <div class="form col-md-6 col-md-offset-3">
                <h1>{{ object.dev_user }}</h1>
                <h3>Edit your profile</h3>
                <p class="alert alert-danger">Header - {% trans 'Image must be 1170x300 minimum.' %}</p>
                <form id="dev_options" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-warning" type="submit" value="{% trans 'Save Profile' %}" class="btn btn-default"/>
                </form>
            </div>


        </div>
    </div>
{% endblock body %}

{% block extra_body %}
    <script src="{% static 'js/jquery.guillotine.min.js' %}"></script>
    <script type="text/javascript">
    $("#crop").attr("src", "{% if object.header %}{{object.header.url}}{% endif %}")
    var picture = $("#crop");
    var coordinates = [{{ object.header_cropping }}];

    picture.on('load', function() {

        picture.guillotine({
            width: 1170,
            height: 300,
            init: {
                scale: 0,
                angle: 0,
                x: coordinates[0],
                y: coordinates[1]
            },
            onChange: function(data, action) { 
                $("#id_header_cropping").val(data.x + "," + data.y + "," +  (data.x + 1170) + "," + (data.y + 300));
            }
        });

    });
/*
    function readURL(input) {
        if (input.files && input.files[0]) {
            $("#id_header_cropping").val("0,0,1170,300");
            var reader = new FileReader();

            reader.onload = function (e) {
                $("#crop").attr('src', e.target.result);
                picture.guillotine('remove');
            }

            reader.readAsDataURL(input.files[0]);
        }
    }*/

var _URL = window.URL || window.webkitURL;
$("#id_header").change(function (e) {
    var file, img;
    if ((file = this.files[0])) {
	var files = this.files[0]
        img = new Image();
        img.onload = function () {
	    if ((this.width > 1170) && (this.height > 300)) {
		    $("#id_header_cropping").val("0,0,1170,300");
		    var reader = new FileReader();

		    reader.onload = function (e) {
			$("#crop").attr('src', e.target.result);
			picture.guillotine('remove');
		    }

		    reader.readAsDataURL(files);
	    } else {
	        alert("{% trans 'Image must be 1170x300 minimum' %}")
		return;
	    }
        };
        img.src = _URL.createObjectURL(file);
    }
});
    $("#id_header").change(function() {
        //readURL(this);
    });

    setInterval(function() {
        $("#crop").css('display', 'inline');
    }, 1000);

    </script>


{% endblock extra_body %}